# Generated by Django 4.1.3 on 2022-11-16 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_itemdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdistribution',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.items'),
        ),
        migrations.AlterField(
            model_name='itemdistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
