# Generated by Django 4.1.3 on 2022-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_pharmacystorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdistribution',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pharmacystorage',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
